### ISSUE TITLE
Release of the training code

### ISSUE THREAD

**Issue by claeyzre** [jingtaozhan/RepCONC#2]
Hello,

Thank you very much for this very interesting paper and open sourcing the results. 
I was wondering if you were planning on releasing the training  code as well ?

Thanks, 

claeyzre

**Comment by jingtaozhan** [comment]
Hi @claeyzre 

Yes, the training code will be open sourced. I'm currently working on it and do some quality check. I hope it can be available by this weekend.

Best,
Jingtao

**Comment by claeyzre** [comment]
Awesome, thank you

**Comment by claeyzre** [comment]
Hello @jingtaozhan, any news on this ?
Thank you

**Comment by Shreeshail-Hingane** [comment]
Hi @jingtaozhan. Had the same query as @claeyzre above. Any updates on when (and if) you will be uploading the training scripts?
Thanks.

**Comment by jingtaozhan** [comment]
I'm recently busy with other stuff, and will have time to prepare the training code in one week. It will definitely be ready before WSDM conference (2.14).

**Comment by jingtaozhan** [comment]
@claeyzre 
I update the code and add examples to compress the index for SBERT, coCondenser, and TAS-B, which I remember we discussed via email. Maybe you are interested in these examples.
